database:
  host: "postgres"
  port: 5432
  username: "admin"
  password: "admin"
  name: "customer-side"
  ssl_mode: "disable"

kafka:
  host: "kafka"
  port: 9092
  ask_for_ggorder_info: "ask_for_ggorder_info"
  ask_for_ggorder_info_edit: "ask_for_ggorder_info_edit"
  provide_ggorder_info: "provide_ggorder_info"

redis:
  host: "redis"
  port: 6379
  db: 0
  ttlSeconds: 600


WarehouseServiceSettings:
  minNameLen: 1
  maxNameLen: 50
  